### ISSUE TITLE
Clarification regarding SNPs used for phasing

### ISSUE THREAD

**Issue by vahidAK** [scottgigante/haplotyped-methylome#2]
Hi @scottgigante ,
I hope you are well,

I read your interesting paper and I have a question regarding SNPs used to phase reads.
What was the source of SNPs? Did you detect the SNPs using illumina sequencing of parental samples?

Thanks,
Vahid.

**Comment by scottgigante** [comment]
Hi @vahidAK , we got the list of SNPs from the Sanger Mouse Genomes Project: https://www.sanger.ac.uk/science/data/mouse-genomes-project
